package abandonedstudio.app.cytrack.utils

object Constants {

    const val MY_DATABASE_NAME = "myDatabase"

    const val LOCATION_PERMISSION_REQUEST_CODE = 0

    const val ACTION_START_OR_RESUME_TRACKING_SERVICE = "ACTION_START_OR_RESUME_TRACKING_SERVICE"

    const val ACTION_PAUSE_TRACKING_SERVICE = "ACTION_PAUSE_TRACKING_SERVICE"

    const val ACTION_END_TRACKING_SERVICE = "ACTION_END_TRACKING_SERVICE"

    const val ACTION_SHOW_MAP_FRAGMENT = "ACTION_SHOW_MAP_FRAGMENT"

    const val TRACKING_NOTIFICATION_CHANNEL_ID = "TRACKING_NOTIFICATION_CHANNEL_ID"

    const val TRACKING_NOTIFICATION_CHANNEL_NAME = "TRACKING"

    const val TRACKING_NOTIFICATION_ID = 1
}